#!/usr/bin/env bash
# .githooks/pre-commit

# 1. Comprobar que no hay archivos con trailing whitespace
if git diff --cached --check; then
  echo " No trailing whitespace."
else
  echo " Trailing whitespace detectado. Corrígelo antes de commitear."
  exit 1
fi



# Si todo OK, regresamos 0 para permitir el commit
exit 0
