version: "3"
services:
  pos_db:
    image: postgres:15
    container_name: pc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=pc_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
