version: "3"
services:
  pos_db:
    image: postgres:15
    container_name: pc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pos_db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./pos_db/seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=pc_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
